include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_single_quotes: true
    non_constant_identifier_names: false
    # TODO: Remove these rules below when production and reorganize your project
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
