# Flutter 3.32.7 - Dart 3.8.1
name: flutter_riverpod_boilerplate
description: A Flutter Project Boilerplate.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0+1
  logger: ^2.6.1
  go_router: ^16.1.0
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^3.0.3
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.3.1
  freezed_annotation: ^3.1.0
  riverpod_annotation: ^3.0.3
  enhanced_enum:
    git:
      url: https://github.com/kxgcayh/enhanced_enum
      path: enhanced_enum

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^3.0.6
  custom_lint: ^0.8.0
  build_runner: ^2.4.6
  flutter_lints: ^6.0.0
  riverpod_lint: ^3.0.3
  json_serializable: ^6.7.1
  go_router_builder: ^4.1.1
  enhanced_enum_generator:
    git:
      url: https://github.com/kxgcayh/enhanced_enum
      path: enhanced_enum_generator
      ref: "1.0.3"

flutter:
  uses-material-design: true
